name: replay_trajectory_classification
channels:
- defaults
- conda-forge
- edeno
- anaconda
dependencies:
- "python >= 3.6"
- numpy
- scipy
- pandas
- numba
- cupy
- statsmodels
- scikit-learn
- scikit-image
- joblib
- seaborn
- networkx
- xarray
- dask
- regularized_glm
- nvtx
- patsy
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- ripple_detection
- loren_frank_data_processing
- track_linearization
- snakeviz
- line_profiler
- memory_profiler
- dask-labextension
- python-graphviz
- nodejs
